DROP TABLE ARYA_OCORRENCIA CASCADE CONSTRAINTS;
DROP TABLE ARYA_DRONE CASCADE CONSTRAINTS;
DROP TABLE ARYA_HUB_OPERACIONAL CASCADE CONSTRAINTS;
DROP TABLE ARYA_USUARIO CASCADE CONSTRAINTS;
DROP TABLE ARYA_ESPECIFICACAO CASCADE CONSTRAINTS;
DROP TABLE ARYA_AREA_OPERACAO CASCADE CONSTRAINTS;
DROP TABLE ARYA_ENDERECO CASCADE CONSTRAINTS;
DROP PROCEDURE insert_arya_usuario;
DROP PROCEDURE update_arya_usuario;
DROP PROCEDURE delete_arya_usuario;
DROP PROCEDURE insert_arya_especificacao;
DROP PROCEDURE update_arya_especificacao;
DROP PROCEDURE delete_arya_especificacao;
DROP PROCEDURE insert_arya_endereco;
DROP PROCEDURE update_arya_endereco;
DROP PROCEDURE delete_arya_endereco;
DROP PROCEDURE insert_arya_area_operacao;
DROP PROCEDURE update_arya_area_operacao;
DROP PROCEDURE delete_arya_area_operacao;
DROP PROCEDURE insert_arya_hub_operacional;
DROP PROCEDURE update_arya_hub_operacional;
DROP PROCEDURE delete_arya_hub_operacional;
DROP PROCEDURE insert_arya_drone;
DROP PROCEDURE update_arya_drone;
DROP PROCEDURE delete_arya_drone;
DROP PROCEDURE insert_arya_ocorrencia;
DROP PROCEDURE update_arya_ocorrencia;
DROP PROCEDURE delete_arya_ocorrencia;
