DROP TABLE ARYA_OCORRENCIA CASCADE CONSTRAINTS;
DROP TABLE ARYA_DRONE CASCADE CONSTRAINTS;
DROP TABLE ARYA_HUB_OPERACIONAL CASCADE CONSTRAINTS;
DROP TABLE ARYA_USUARIO CASCADE CONSTRAINTS;
DROP TABLE ARYA_ESPECIFICACAO CASCADE CONSTRAINTS;
DROP TABLE ARYA_AREA_OPERACAO CASCADE CONSTRAINTS;
DROP TABLE ARYA_ENDERECO CASCADE CONSTRAINTS;