CREATE TABLE USUARIO (
    usuario_id      NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    nome            VARCHAR2(255) NOT NULL,
    email           VARCHAR2(255) UNIQUE NOT NULL,
    senha           VARCHAR2(255) NOT NULL,
    data_criacao    TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE REGIAO (
    regiao_id           NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    bairro              VARCHAR2(255) NOT NULL,
    municipio           VARCHAR2(255) NOT NULL,
    estado              VARCHAR2(2) NOT NULL,
    classificacao_risco VARCHAR2(10) CHECK (classificacao_risco IN ('Baixo', 'Médio', 'Alto')) NOT NULL
);

CREATE TABLE OCORRENCIA (
    ocorrencia_id       NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    regiao_id           NUMBER NOT NULL,
    tipo_ocorrencia     VARCHAR2(100) NOT NULL,
    nivel_severidade    VARCHAR2(10) CHECK (nivel_severidade IN ('Leve', 'Moderado', 'Crítico')) NOT NULL,
    data_ocorrencia     TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    descricao           VARCHAR2(1000),
    CONSTRAINT fk_ocorrencia_regiao FOREIGN KEY (regiao_id) REFERENCES REGIAO(regiao_id)
);

CREATE TABLE CADASTRO_USUARIO (
    cadastro_id     NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    usuario_id      NUMBER NOT NULL,
    ocorrencia_id   NUMBER NOT NULL,
    data_cadastro   TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    observacoes     VARCHAR2(500),
    CONSTRAINT fk_cadastro_usuario_usuario FOREIGN KEY (usuario_id) REFERENCES USUARIO(usuario_id),
    CONSTRAINT fk_cadastro_usuario_ocorrencia FOREIGN KEY (ocorrencia_id) REFERENCES OCORRENCIA(ocorrencia_id)
);

CREATE TABLE DRONE (
    drone_id        NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    modelo          VARCHAR2(100) NOT NULL,
    fabricante      VARCHAR2(100) NOT NULL,
    ativo           CHAR(1) CHECK (ativo IN ('S', 'N')) NOT NULL,
    regiao_id       NUMBER,
    CONSTRAINT fk_drone_regiao FOREIGN KEY (regiao_id) REFERENCES REGIAO(regiao_id)
);

CREATE TABLE CADASTRO_DRONE (
    cadastro_drone_id   NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    usuario_id          NUMBER NOT NULL,
    drone_id            NUMBER NOT NULL,
    data_cadastro       TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    status_operacao     VARCHAR2(50) NOT NULL,
    notas               VARCHAR2(500),
    CONSTRAINT fk_cadastro_drone_usuario FOREIGN KEY (usuario_id) REFERENCES USUARIO(usuario_id),
    CONSTRAINT fk_cadastro_drone_drone FOREIGN KEY (drone_id) REFERENCES DRONE(drone_id)
);