DROP TABLE ARYA_MISSAO_DRONE CASCADE CONSTRAINTS;
DROP TABLE ARYA_OCORRENCIA CASCADE CONSTRAINTS;
DROP TABLE ARYA_DRONE CASCADE CONSTRAINTS;
DROP TABLE ARYA_HUB_OPERACIONAL CASCADE CONSTRAINTS;
DROP TABLE ARYA_AREA_OPERACAO CASCADE CONSTRAINTS;
DROP TABLE ARYA_USUARIO CASCADE CONSTRAINTS;
DROP TABLE ARYA_ENDERECO CASCADE CONSTRAINTS;
DROP PROCEDURE insert_arya_usuario;
DROP PROCEDURE update_arya_usuario;
DROP PROCEDURE delete_arya_usuario;
DROP PROCEDURE insert_arya_especificacao;
DROP PROCEDURE update_arya_especificacao;
DROP PROCEDURE delete_arya_especificacao;
DROP PROCEDURE insert_arya_endereco;
DROP PROCEDURE update_arya_endereco;
DROP PROCEDURE delete_arya_endereco;
DROP PROCEDURE insert_arya_area_operacao;
DROP PROCEDURE update_arya_area_operacao;
DROP PROCEDURE delete_arya_area_operacao;
DROP PROCEDURE insert_arya_hub_operacional;
DROP PROCEDURE update_arya_hub_operacional;
DROP PROCEDURE delete_arya_hub_operacional;
DROP PROCEDURE insert_arya_drone;
DROP PROCEDURE update_arya_drone;
DROP PROCEDURE delete_arya_drone;
DROP PROCEDURE insert_arya_ocorrencia;
DROP PROCEDURE update_arya_ocorrencia;
DROP PROCEDURE delete_arya_ocorrencia;
DROP PROCEDURE insert_missao_drone;
DROP PROCEDURE update_missao_drone;
DROP PROCEDURE delete_missao_drone;
DROP FUNCTION pontuacao_severidade;
DROP FUNCTION ranking_ocorrencias_hub;
DROP FUNCTION calcula_risco;
DROP PACKAGE pkg_arya_management;
DROP TRIGGER arya_usuario_validacao;
DROP TRIGGER arya_endereco_validacao;
DROP TRIGGER arya_area_operacao_validacao;
DROP TRIGGER arya_hub_operacional_validacao;
DROP TRIGGER arya_drone_validacao;
DROP TRIGGER arya_ocorrencia_validacao;
DROP TRIGGER arya_missao_drone_validacao;
